name: Deploy Storybook to Pages

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: storybook-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install pnpm (best effort)
        run: |
          set -e
          npm i -g pnpm@9 || echo "pnpm global install failed; will use npm fallback"

      - name: Install dependencies (pnpm or npm)
        run: |
          if command -v pnpm >/dev/null 2>&1; then
            echo "Using pnpm to install"
            pnpm install --frozen-lockfile || (echo "pnpm install failed; falling back to npm ci" && npm ci)
          else
            echo "pnpm not found; using npm ci"
            npm ci
          fi

      - name: Build Storybook (pnpm or npm)
        run: |
          if command -v pnpm >/dev/null 2>&1; then
            pnpm build-storybook || (echo "pnpm build failed; npm fallback" && npx storybook build)
          else
            npx storybook build
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
